[env]
REDDIT_APP_ID=""
REDDIT_SECRET_KEY=""
TWITTER_ACCESS_KEY=""
TWITTER_ACCESS_SECRET=""
TWITTER_API_SECRET=""
TWITTER_API_KEY=""
TWITTER_BEARER_TOKEN=""
NEO_ENDPOINT=""
NEO_USER=""
NEO_PASSWORD=""
OPENAI_KEY=""
REPLICATE_KEY=""